### PR TITLE
Add DSC-RX1.hdr

### PR DESCRIPTION
**Pull request by undingen**
With this patch one can change the language setting on the RX1 :-).
https://github.com/ma1co/fwtool.py/pull/17

Thank you very much!

### CODE REVIEW

**Comment by ma1co** [comment]
Thank you! I would be very grateful if you could dump the firmware. Using updatershell, run the following commands: `pull /dev/nflasha` and `bootloader`
It would be great if you could zip the resulting files (`nflasha` and `boot`) and upload them to my [dropbox](https://www.dropbox.com/request/WXQ1IKIoPo4ECK8CFxRx). Thanks for your help!

**Comment by hypoxic** [comment]
Perhaps after a system reset as I don't wand my SSIDs/PW pairs exposed.

Do you have some sample QEMU command lines for the bionz processor? I got
them loaded, but I may be using the wrong bootrom. I was just loading the
binary located at FFFF0000-FFFF6000.

**Comment by trapmat** [comment]
hi, are there any news for the rx1? unfortunately it is not yet compatible with pmca gui. how did you change the language?
thank youu

**Comment by HCX-star** [comment]
> 嗨，RX1有什么消息吗？不幸的是，它尚未与PMCA GUI兼容。你是如何改变语言的？谢谢

Hello, I am now giving my Sony RX1r to update the language, have you solved it? I want to ask, because when I use the gui it shows that the installation of the driver failed, I don't know what the reason is, I want to solve this problem, can you give me an answer if you see it? Thank you/

**Comment by HCX-star** [comment]
> 使用此补丁，可以更改 RX1 上的语言设置 ：-）。[MA1co/FWtool.py#17](https://github.com/ma1co/fwtool.py/pull/17)
> 
> 谢谢！

Hello, I am now giving my Sony RX1r to update the language, have you solved it? I want to ask, because when I use the gui it shows that the installation of the driver failed, I don't know what the reason is, I want to solve this problem, can you give me an answer if you see it? Thank you/

**Pull request merged**
